---
- name: Fix problem
  hosts: localhost
 
  tasks:
 
  - name: Fix problem
    uri:
      url: http://52.191.84.29:8080/services/ConfigurationService/setPluginEnabled?name=LoginProblems&enabled=false      
      status_code: [200, 201, 202]
      return_content: no
    register: this
