---
- name: Fix problem
  hosts: all
 
  tasks:
 
  - name: Fix problem
    uri:
      url: http://104.45.187.222:8080/services/ConfigurationService/setPluginEnabled?name=BadCacheSynchronization&enabled=false      
      status_code: [200, 201, 202]
      return_content: no
    register: this
